# Generated by Django 5.0.3 on 2024-04-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_order_id_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
    ]
