# Generated by Django 5.0.3 on 2024-04-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
