version: "3"

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  django:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      USER: admin
      POSTGRES_URL: postgres